widgets:
    # Profile widget configurations
    -
        # Where should the widget be placed, left sidebar or right sidebar
        position: left
        type: profile
        # Author name
        author: 守希
        # Author title
        author_title: Cloud,DevOps,SRE
        # Author's current location
        location: Shanghai
        # URL or path to the avatar image
        avatar: /img/avatar-fish.jpg
        # Whether show the rounded avatar image
        avatar_rounded: true
        # Email address for the Gravatar
        gravatar: 
        # URL or path for the follow button
        follow_link: https://www.mikesay.com/
        # Links to be shown on the bottom of the profile widget
        social_links: 
            Github:
                icon: fab fa-github
                url: https://github.com/mikesay
            Facebook:
                icon: fab fa-facebook
                url: https://facebook.com
            Twitter:
                icon: fab fa-twitter
                url: https://twitter.com
            Dribbble:
                icon: fab fa-dribbble
                url: https://dribbble.com
            RSS:
                icon: fas fa-rss
                url: /
    # Table of contents widget configurations
    -
        # Where should the widget be placed, left sidebar or right sidebar
        position: left
        type: toc
    -
        type: categories
        position: left
    -
        type: tags
        position: left